import { Copy, Plus, Trash2 } from 'lucide-react'
import type { ReactNode } from 'react'
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { SortableContext, rectSortingStrategy, sortableKeyboardCoordinates } from '@dnd-kit/sortable'
import { useResume } from '../resumeStore'
import { SortableItem } from './SortableItem'

type Collection = 'experience' | 'education' | 'skills' | 'languages' | 'projects' | 'certifications'

function SortableGroup({ collection, ids, children }: { collection: Collection; ids: string[]; children: ReactNode }) {
  const { dispatch } = useResume()
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }))
  const handleDragEnd = ({ active, over }: DragEndEvent) => { if (over && active.id !== over.id) dispatch({ type: 'reorder-items', collection, activeId: String(active.id), overId: String(over.id) }) }
  return <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}><SortableContext items={ids} strategy={rectSortingStrategy}>{children}</SortableContext></DndContext>
}

function Field({ label, value, onChange, type = 'text', placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) {
  return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>
}

function SectionHeader({ eyebrow, title, collection }: { eyebrow: string; title: string; collection: Collection }) {
  const { dispatch } = useResume()
  return <div className="card-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button className="secondary-button" onClick={() => dispatch({ type: 'add-item', collection })}><Plus size={15} /> Agregar</button></div>
}

function ItemActions({ collection, id }: { collection: Collection; id: string }) {
  const { dispatch } = useResume()
  return <div className="item-actions"><button className="tiny-button" onClick={() => dispatch({ type: 'duplicate-item', collection, id })} aria-label="Duplicar elemento"><Copy size={14} /></button><button className="tiny-button danger" onClick={() => dispatch({ type: 'remove-item', collection, id })} aria-label="Eliminar elemento"><Trash2 size={14} /></button></div>
}

export function ContentSections() {
  const { resume, dispatch } = useResume()
  const update = (collection: Collection, id: string, field: string, value: string | boolean) => dispatch({ type: 'update-item', collection, id, field, value })
  return <>
    <section className="editor-card"><SectionHeader eyebrow="03 / Trayectoria" title="Experiencia" collection="experience" />
      <SortableGroup collection="experience" ids={resume.experience.map((item) => item.id)}><div className="repeatable-list">{resume.experience.map((item) => <SortableItem id={item.id} className="repeatable-card" key={item.id}><div className="repeatable-heading"><strong>{item.role || 'Nueva experiencia'}</strong><ItemActions collection="experience" id={item.id} /></div><div className="form-grid"><Field label="Cargo" value={item.role} onChange={(value) => update('experience', item.id, 'role', value)} placeholder="Software Developer" /><Field label="Empresa" value={item.company} onChange={(value) => update('experience', item.id, 'company', value)} placeholder="Empresa XYZ" /><Field label="Ubicación" value={item.location} onChange={(value) => update('experience', item.id, 'location', value)} /><Field label="Inicio" value={item.startDate} onChange={(value) => update('experience', item.id, 'startDate', value)} placeholder="Ene 2024" /><Field label="Final" value={item.endDate} onChange={(value) => update('experience', item.id, 'endDate', value)} placeholder="Actualidad" /><label className="check-field"><input type="checkbox" checked={item.current} onChange={(event) => update('experience', item.id, 'current', event.target.checked)} /> Trabajo aquí actualmente</label><label className="field full"><span>Descripción</span><textarea value={item.description} onChange={(event) => update('experience', item.id, 'description', event.target.value)} rows={3} /></label></div></SortableItem>)}</div></SortableGroup>
    </section>
    <section className="editor-card"><SectionHeader eyebrow="04 / Formación" title="Educación" collection="education" />
      <SortableGroup collection="education" ids={resume.education.map((item) => item.id)}><div className="repeatable-list">{resume.education.map((item) => <SortableItem id={item.id} className="repeatable-card" key={item.id}><div className="repeatable-heading"><strong>{item.degree || 'Nueva formación'}</strong><ItemActions collection="education" id={item.id} /></div><div className="form-grid"><Field label="Título" value={item.degree} onChange={(value) => update('education', item.id, 'degree', value)} placeholder="Ingeniería de Sistemas" /><Field label="Institución" value={item.institution} onChange={(value) => update('education', item.id, 'institution', value)} /><Field label="Ubicación" value={item.location} onChange={(value) => update('education', item.id, 'location', value)} /><Field label="Inicio" value={item.startDate} onChange={(value) => update('education', item.id, 'startDate', value)} /><Field label="Final" value={item.endDate} onChange={(value) => update('education', item.id, 'endDate', value)} /><label className="check-field"><input type="checkbox" checked={item.current} onChange={(event) => update('education', item.id, 'current', event.target.checked)} /> Estudio aquí actualmente</label><label className="field full"><span>Descripción y logros</span><textarea value={item.description} onChange={(event) => update('education', item.id, 'description', event.target.value)} rows={2} /></label></div></SortableItem>)}</div></SortableGroup>
    </section>
    <section className="editor-card"><SectionHeader eyebrow="05 / Capacidades" title="Habilidades e idiomas" collection="skills" /><div className="compact-grid"><div><h3>Habilidades</h3><SortableGroup collection="skills" ids={resume.skills.map((item) => item.id)}>{resume.skills.map((item) => <SortableItem id={item.id} className="compact-row" key={item.id}><input value={item.name} placeholder="React" onChange={(event) => update('skills', item.id, 'name', event.target.value)} /><select value={item.level} onChange={(event) => update('skills', item.id, 'level', event.target.value)}><option>Principiante</option><option>Básico</option><option>Intermedio</option><option>Avanzado</option><option>Experto</option></select><button className="tiny-button danger" onClick={() => dispatch({ type: 'remove-item', collection: 'skills', id: item.id })} aria-label="Eliminar habilidad"><Trash2 size={14} /></button></SortableItem>)}</SortableGroup><button className="text-button" onClick={() => dispatch({ type: 'add-item', collection: 'skills' })}><Plus size={14} /> Habilidad</button></div><div><h3>Idiomas</h3><SortableGroup collection="languages" ids={resume.languages.map((item) => item.id)}>{resume.languages.map((item) => <SortableItem id={item.id} className="compact-row" key={item.id}><input value={item.name} placeholder="Inglés" onChange={(event) => update('languages', item.id, 'name', event.target.value)} /><select value={item.level} onChange={(event) => update('languages', item.id, 'level', event.target.value)}><option>A1</option><option>A2</option><option>B1</option><option>B2</option><option>C1</option><option>C2</option><option>Nativo</option></select><button className="tiny-button danger" onClick={() => dispatch({ type: 'remove-item', collection: 'languages', id: item.id })} aria-label="Eliminar idioma"><Trash2 size={14} /></button></SortableItem>)}</SortableGroup><button className="text-button" onClick={() => dispatch({ type: 'add-item', collection: 'languages' })}><Plus size={14} /> Idioma</button></div></div></section>
    <section className="editor-card"><SectionHeader eyebrow="06 / Trabajo destacado" title="Proyectos" collection="projects" /><SortableGroup collection="projects" ids={resume.projects.map((item) => item.id)}><div className="repeatable-list">{resume.projects.map((item) => <SortableItem id={item.id} className="repeatable-card" key={item.id}><div className="repeatable-heading"><strong>{item.name || 'Nuevo proyecto'}</strong><ItemActions collection="projects" id={item.id} /></div><div className="form-grid"><Field label="Nombre" value={item.name} onChange={(value) => update('projects', item.id, 'name', value)} /><Field label="Rol" value={item.role} onChange={(value) => update('projects', item.id, 'role', value)} /><Field label="Tecnologías" value={item.technologies} onChange={(value) => update('projects', item.id, 'technologies', value)} /><Field label="Fecha" value={item.date} onChange={(value) => update('projects', item.id, 'date', value)} /><Field label="GitHub" value={item.github} onChange={(value) => update('projects', item.id, 'github', value)} /><Field label="Demo" value={item.demo} onChange={(value) => update('projects', item.id, 'demo', value)} /><label className="field full"><span>Descripción</span><textarea value={item.description} onChange={(event) => update('projects', item.id, 'description', event.target.value)} rows={2} /></label></div></SortableItem>)}</div></SortableGroup></section>
    <section className="editor-card"><SectionHeader eyebrow="07 / Credenciales" title="Certificaciones" collection="certifications" /><div className="repeatable-list">{resume.certifications.map((item) => <div className="repeatable-card" key={item.id}><div className="repeatable-heading"><strong>{item.name || 'Nueva certificación'}</strong><ItemActions collection="certifications" id={item.id} /></div><div className="form-grid"><Field label="Nombre" value={item.name} onChange={(value) => update('certifications', item.id, 'name', value)} /><Field label="Institución" value={item.institution} onChange={(value) => update('certifications', item.id, 'institution', value)} /><Field label="Fecha" value={item.date} onChange={(value) => update('certifications', item.id, 'date', value)} /><Field label="Credential ID" value={item.credentialId} onChange={(value) => update('certifications', item.id, 'credentialId', value)} /><Field label="URL" value={item.url} onChange={(value) => update('certifications', item.id, 'url', value)} /></div></div>)}</div></section>
  </>
}