import { Columns3, Palette, SlidersHorizontal, Type } from 'lucide-react'
import { useResume } from '../resumeStore'
import type { ResumeData } from '../types'

export function DesignPanel() {
  const { resume, dispatch } = useResume()
  const update = (field: keyof ResumeData['design'], value: string | number | boolean) => dispatch({ type: 'update-design', field, value })
  const { design } = resume
  return <section className="editor-card design-panel"><div className="card-heading"><div><span className="eyebrow">Personalización</span><h2>Define tu lenguaje visual</h2></div><SlidersHorizontal size={19} color={design.accent} /></div><p className="card-description">Los cambios se aplican al instante en todas las páginas del CV.</p>
    <div className="design-block"><div className="design-block-title"><Palette size={15} /><strong>Paleta</strong></div><div className="color-controls"><label className="color-field"><span>Principal</span><input type="color" value={design.accent} onChange={(event) => update('accent', event.target.value)} /><code>{design.accent}</code></label><label className="color-field"><span>Secundario</span><input type="color" value={design.secondary} onChange={(event) => update('secondary', event.target.value)} /><code>{design.secondary}</code></label></div></div>
    <div className="design-block"><div className="design-block-title"><Type size={15} /><strong>Tipografía y jerarquía</strong></div><div className="form-grid"><label className="field"><span>Tipografía</span><select value={design.font} onChange={(event) => update('font', event.target.value)}><option value="Inter">Inter</option><option value="Georgia">Georgia</option><option value="Trebuchet MS">Trebuchet MS</option></select></label><label className="field"><span>Tamaño base</span><input type="number" min="8" max="12" step="1" value={design.fontSize} onChange={(event) => update('fontSize', Number(event.target.value))} /></label><label className="field"><span>Estilo de títulos</span><select value={design.titleStyle} onChange={(event) => update('titleStyle', event.target.value)}><option value="uppercase">Mayúsculas</option><option value="sentence">Normal</option><option value="line">Con línea</option></select></label><label className="field"><span>Estilo de fechas</span><select value={design.dateStyle} onChange={(event) => update('dateStyle', event.target.value)}><option value="inline">En línea</option><option value="muted">Discreto</option></select></label></div></div>
    <div className="design-block"><div className="design-block-title"><Columns3 size={15} /><strong>Espacio y columnas</strong></div><div className="range-grid"><label><span>Espaciado <b>{design.spacing.toFixed(1)}x</b></span><input type="range" min=".7" max="1.4" step=".1" value={design.spacing} onChange={(event) => update('spacing', Number(event.target.value))} /></label><label><span>Interlineado <b>{design.lineHeight.toFixed(2)}</b></span><input type="range" min="1.2" max="1.9" step=".05" value={design.lineHeight} onChange={(event) => update('lineHeight', Number(event.target.value))} /></label><label><span>Márgenes <b>{design.margins}%</b></span><input type="range" min="6" max="15" step="1" value={design.margins} onChange={(event) => update('margins', Number(event.target.value))} /></label><label><span>Ancho lateral <b>{design.columnWidth}%</b></span><input type="range" min="25" max="42" step="1" value={design.columnWidth} onChange={(event) => update('columnWidth', Number(event.target.value))} /></label></div></div>
    <div className="design-toggles"><label><input type="checkbox" checked={design.showIcons} onChange={(event) => update('showIcons', event.target.checked)} /> Mostrar iconos de contacto</label><label><input type="checkbox" checked={design.showSkillLevels} onChange={(event) => update('showSkillLevels', event.target.checked)} /> Mostrar niveles de habilidades</label></div>
  </section>
}
